- name: three tier
  hosts: localhost
  become: true
  tasks:
    - name: installation of nginx
      apt:
        name: nginx
        state: present
      notify: restart nginx

    - name: starting nginx
      service:
        name: nginx
        state: started

    - name: installation of php
      apt:
        name: php
        state: present

    - name: installation of php-fpm
      apt:
        name: php-fpm
        state: present
      notify: restart php-fpm

    - name: installing mariadb
      apt:
        name: mariadb-server
        state: present
      notify: restart mariadb

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart php-fpm
      service:
        name: php-fpm
        state: restarted

    - name: restart mariadb
      service:
        name: mariadb-server
        state: restarted
