apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: mypod
   labels:
      env: dev
spec:
    replicas: 3
    selector:
      matchLabels:
          env: dev
    template:
       metadata:
         labels:
            env: dev
       spec:
           containers:
             - name: mynginx
               image: nginx
               ports:
                 - containerPort: 80
